fos_rest:
    routing_loader: false

    format_listener:
        rules:
            - {
                  path: ^/api,
                  prefer_extension: false,
                  fallback_format: html,
                  priorities: [multipart, json, html],
              }
            - { path: ^/, stop: true }
