parameters:
    image_directory: "%kernel.project_dir%/public/uploads"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Service\ImageUploadService:
        arguments:
            $imageDir: "%image_directory%"

    App\Contract\UserRegistrationInterface: '@App\Service\UserRegistrationService'
    App\Contract\HotelInterface: '@App\Service\HotelService'
    App\Contract\HotelImageInterface: '@App\Service\ImageUploadService'
    App\Contract\RoomInterface: '@App\Service\RoomService'
    App\Contract\RoomImageInterface: '@App\Service\ImageUploadService'
    App\Contract\BookingInterface: '@App\Service\BookingService'

    App\Security\Voter\RoleVoter:
        arguments:
            $kernel: "@kernel"
